const IMG='../../assets/images/';
const CONTACT={phone:'+49 160 5086983',email:'kontakt@pfalz-loadout.de',city:'67551 Worms',whatsapp:'https://wa.me/491605086983'};
const SERVICES=[
 {id:'ecommerce',icon:'shopping-cart',title:'E-Commerce',short:'Digitaler Handel mit Fokus auf Effizienz',text:'Wir betreiben eigene E-Commerce-Plattformen und vertreiben unsere Sortimente über Online-Shops sowie etablierte Marktplätze. Unser Multichannel-Ansatz ermöglicht eine breite Marktabdeckung bei schlanken Prozessen, von der Beschaffung über das Listing bis zum Fulfillment.',image:IMG+'ecommerce-shop.png'},
 {id:'reselling',icon:'recycle',title:'Reselling & Asset Recovery',short:'Werterhalt statt Abschreibung',text:'Überbestände, Restposten und Retourenware binden Kapital und Lagerfläche. Wir kaufen Warenbestände an, bereiten sie auf und führen sie über unsere Vertriebskanäle in den Markt zurück. Für unsere Partner bedeutet das schnelle Liquidität, reduzierte Lagerkosten und einen nachhaltigen Umgang mit Ressourcen.',image:IMG+'reselling-ware.png'},
 {id:'storage',icon:'warehouse',title:'Storage Solutions',short:'Lagerkapazität nach Bedarf',text:'Wir stellen Lagerflächen für temporäre und langfristige Anforderungen bereit, skalierbar und ohne starre Vertragsbindung. Für Gewerbekunden mit saisonalen Spitzen ebenso wie für Privatkunden in Übergangsphasen.',image:IMG+'storage-unit.png'},
 {id:'clearance',icon:'truck',title:'Clearance Services',short:'Strukturierte Räumung, fachgerechte Verwertung',text:'Vollständige Räumung von Garagen, Lagern, Hallen und Gewerbeflächen: Bestandsaufnahme, verbindliches Angebot, Durchführung und besenreine Übergabe. Verwertbare Bestände werden in den Wirtschaftskreislauf zurückgeführt, alles Weitere fachgerecht entsorgt.',image:IMG+'transporter-verladung.png'},
 {id:'web',icon:'monitor-cog',title:'Web Maintenance & Management',short:'Stabile Systeme, aktuelle Inhalte',text:'Laufende technische Betreuung von Websites und Online-Shops: Updates, Sicherheitsmonitoring, Content-Pflege und Systemverwaltung. Aus dem Betrieb eigener E-Commerce-Plattformen bringen wir praxisnahes Know-how mit.',image:IMG+'webseite-laptop.png'},
 {id:'facility',icon:'wrench',title:'Solutions & Support',short:'Für jede Aufgabe eine schnelle Lösung',text:'Nicht jede Anforderung passt in eine feste Kategorie. Ob kurzfristiger Engpass, organisatorische Herausforderung oder ein Anliegen, für das es keinen passenden Ansprechpartner gibt: Wir analysieren die Situation, entwickeln eine pragmatische Lösung und setzen sie zuverlässig um. Flexibel, lösungsorientiert und mit einem Netzwerk, das wir bei Bedarf einbinden.',image:IMG+'wartung-technik.png'},
 {id:'smarthome',side:true,icon:'lightbulb',title:'Smart Home & KNX',short:'Programmierung von Gebäudeautomation',text:'Als ergänzende Leistung übernehmen wir die Programmierung von Smart-Home-Systemen auf KNX-Basis: Parametrierung mit der ETS, Einrichtung von Licht-, Jalousie- und Heizungssteuerung, Szenen und Visualisierung sowie Anpassungen an bestehenden Anlagen.',image:IMG+'smarthome-knx.png'}
];
const NAV=[{label:'Leistungen',id:'leistungen',children:SERVICES.map(s=>({label:s.title,id:s.id,icon:s.icon}))},{label:'Über uns',id:'ueber'},{label:'Kontakt',id:'kontakt'}];
const FOOTER_COLS=[{title:'Leistungen',links:SERVICES.map(s=>({label:s.title,id:s.id}))}];
const USPS=[{title:'Alles aus einer Hand',text:'Ein Kontakt für alle Aufgaben statt vieler einzelner Dienstleister.',lines:['Ein Kontakt für alle Aufgaben statt','vieler einzelner Dienstleister.']},{title:'Verbindliche Angebote',text:'Sie kennen Umfang und Kosten, bevor wir beginnen.',lines:['Sie kennen Umfang und Kosten,','bevor wir beginnen.']},{title:'Schnell vor Ort',text:'Regional in Worms verankert und kurzfristig einsatzbereit.'}];
const STEPS=[['01','Anfrage','Sie schildern Ihr Anliegen per Formular, Telefon oder WhatsApp.'],['02','Bedarfsanalyse','Persönliches Gespräch oder Besichtigung vor Ort.'],['03','Angebot','Verbindlich und mit transparentem Leistungsumfang.'],['04','Umsetzung','Termingerecht, und wir bleiben Ihr Ansprechpartner.']];
const AREA=['Worms','Frankenthal','Ludwigshafen','Mannheim','Alzey','Grünstadt','Bensheim'];
const REVIEWS=[
 {quote:'[Kundenstimme zu einer Räumung oder Entrümpelung]',name:'[Name, gekürzt]',meta:'Privatkunde, [Ort]'},
 {quote:'[Kundenstimme zum Warenankauf oder zur Lagerung]',name:'[Firmenname]',meta:'Gewerbekunde, [Ort]'},
 {quote:'[Kundenstimme zur Website- oder Objektbetreuung]',name:'[Firmenname]',meta:'Gewerbekunde, [Ort]'}
];
const PROJECTS=[{title:'Garagenräumung, [Ort]',text:'[Kurzbeschreibung des Projekts]',ph:'Foto: Garagenräumung vorher/nachher'},{title:'Einlagerung Gewerbeware, [Ort]',text:'[Kurzbeschreibung des Projekts]',ph:'Foto: Lagerfläche'},{title:'Website-Betreuung, [Kunde]',text:'[Kurzbeschreibung des Projekts]',ph:'Foto/Screenshot: Website'}];
Object.assign(window,{SERVICES,NAV,FOOTER_COLS,USPS,STEPS,AREA,REVIEWS,PROJECTS,IMG,CONTACT});
